import type { ScamCategory } from '../types.js';

/**
 * Rule set for the offline pattern engine. Patterns are written for German and
 * English scam texts common in the DACH region. Each pattern is wrapped with
 * Unicode-aware word boundaries (JS `\b` does not understand umlauts).
 *
 * Weights are probabilities-ish (0–1) and are combined with noisy-OR, so a few
 * strong signals or many weak ones both push the score up.
 */
export interface Rule {
  id: string;
  group: string;
  label: string;
  weight: number;
  categories: ScamCategory[];
  patterns: string[];
}

export const RULES: Rule[] = [
  // ── Druck & Drohungen ─────────────────────────────────────────────
  {
    id: 'urgency',
    group: 'pressure',
    label: 'Zeitdruck wird aufgebaut',
    weight: 0.22,
    categories: ['phishing'],
    patterns: [
      'innerhalb (?:von |der nächsten )?\\d+ ?(?:stunden|std\\.?|h|tagen?|minuten)',
      'within \\d+ (?:hours|days|minutes)',
      'heute noch',
      'nur noch heute',
      'letzte (?:mahnung|warnung|chance|erinnerung|aufforderung)',
      'final (?:notice|warning|reminder)',
      'sofort(?:ig)?',
      'umgehend',
      'unverzüglich',
      'dringend',
      'urgent',
      'immediately',
      'act now',
      'läuft (?:heute|morgen|bald) ab',
      'frist (?:läuft|endet)',
      'nur noch \\d+ (?:stück|exemplare|plätze|artikel)',
    ],
  },
  {
    id: 'account_threat',
    group: 'pressure',
    label: 'Drohung mit Kontosperrung',
    weight: 0.38,
    categories: ['phishing'],
    patterns: [
      '(?:konto|account|zugang|karte|kreditkarte|profil)(?: \\p{L}+){0,3} (?:wird|wurde|werden) (?:vorübergehend |vorläufig |endgültig )?(?:gesperrt|eingeschränkt|deaktiviert|gelöscht|eingefroren)',
      '(?:sperrung|einschränkung|deaktivierung) (?:ihres|deines) (?:kontos|zugangs|accounts)',
      '(?:wird|wurde|werden) (?:ihr|dein|ihre|deine) [\\p{L}-]*(?:konto|zugang|account|karte) (?:vorübergehend |vorläufig |endgültig )?(?:gesperrt|eingeschränkt|deaktiviert|gelöscht)',
      'account (?:will be |has been )?(?:suspended|locked|disabled|limited|closed)',
      'ungewöhnliche aktivitäten?',
      'verdächtige (?:aktivität|anmeldung|transaktion)',
      'unusual (?:activity|sign-?in)',
    ],
  },
  {
    id: 'legal_threat',
    group: 'pressure',
    label: 'Drohung mit Polizei, Gericht oder Inkasso',
    weight: 0.3,
    categories: ['impersonation'],
    patterns: [
      'haftbefehl',
      'strafanzeige',
      'anzeige (?:wird |wurde )?erstattet',
      'staatsanwaltschaft',
      'strafverfahren',
      'europol',
      'interpol',
      'inkasso\\p{L}*',
      'pfändung',
      'gerichtsvollzieher',
      'arrest warrant',
      'legal action',
    ],
  },

  // ── Datenabfrage ──────────────────────────────────────────────────
  {
    id: 'credentials',
    group: 'data',
    label: 'Fragt nach Passwort, PIN, TAN oder Codes',
    weight: 0.5,
    categories: ['phishing'],
    patterns: [
      '(?:gib|gebe|geben sie|bestätige|bestätigen sie|verifiziere|teile|teilen sie|sende|senden sie|schick|schicke|nenne|nennen sie|leite|tippe)(?: \\p{L}+){0,5} (?:dein|deine|ihr|ihre|den|die|das|mir)?(?: \\p{L}+)? ?(?:passwort|kennwort|pin|tan|pushtan|zugangsdaten|anmeldedaten|login-?daten|bestätigungscode|sms-?code|code)',
      '(?:passwort|kennwort|pin|tan|zugangsdaten|bestätigungscode|sms-?code|6-?stelligen code)(?: \\p{L}+){0,5} (?:mitteilen|senden|schicken|eingeben|nennen|weiterleiten|zurückschicken)',
      '(?:verify|confirm) your (?:account|identity|password|login)',
      'enter your (?:password|pin|code)',
      'code (?:den |welchen )?(?:du|ich) (?:gerade |eben )?(?:per sms )?(?:bekommen|erhalten)',
    ],
  },
  {
    id: 'verify_data',
    group: 'data',
    label: 'Daten sollen „bestätigt“ oder „aktualisiert“ werden',
    weight: 0.34,
    categories: ['phishing'],
    patterns: [
      '(?:daten|kundendaten|angaben|informationen|zahlungsdaten|adresse)(?: \\p{L}+){0,3} (?:zu )?(?:aktualisieren|bestätigen|verifizieren|abgleichen|vervollständigen)',
      '(?:verifizierung|legitimation|aktualisierung|bestätigung) (?:ist )?(?:erforderlich|notwendig|ausstehend)',
      'identität (?:zu )?(?:bestätigen|verifizieren)',
      '(?:bestätige|bestätigen sie|aktualisiere|aktualisieren sie|verifiziere|verifizieren sie|vervollständige)(?: \\p{L}+){0,3} (?:daten|angaben|identität|konto|zahlungsdaten|adresse|kundendaten)',
      '(?:pushtan|tan|banking|sicherheits)-?(?:verfahren|app|zugang)(?: [\\p{L}\\d.]+){0,5} (?:aktualisier\\p{L}*|erneuer\\p{L}*|bestätig\\p{L}*|verifizier\\p{L}*)',
      'sicherheits-?update',
      'update your (?:payment|billing|account) (?:details|information|method)',
    ],
  },
  {
    id: 'card_data',
    group: 'data',
    label: 'Fragt nach Kreditkarten- oder Bankdaten',
    weight: 0.42,
    categories: ['phishing'],
    patterns: [
      'kreditkarten-?(?:daten|nummer|informationen)',
      'kartennummer',
      'cvv',
      'cvc',
      'prüfziffer',
      'ablaufdatum (?:der|ihrer|deiner) karte',
      'card (?:number|details)',
      'iban(?: \\p{L}+){0,4} (?:angeben|eingeben|bestätigen|mitteilen)',
    ],
  },
  {
    id: 'id_documents',
    group: 'data',
    label: 'Verlangt Ausweis, Selfie oder Video-Ident',
    weight: 0.3,
    categories: ['job', 'phishing'],
    patterns: [
      'ausweiskopie',
      'kopie (?:ihres|deines) (?:ausweises|personalausweises|reisepasses)',
      'foto (?:ihres|deines|vom) (?:ausweis|personalausweis)',
      'selfie mit (?:dem |ihrem |deinem )?ausweis',
      'video-?ident\\p{L}*',
      'postident',
      'photo of your (?:id|passport)',
    ],
  },
  {
    id: 'remote_access',
    group: 'data',
    label: 'Fernwartungs-Software soll installiert werden',
    weight: 0.55,
    categories: ['tech_support', 'investment'],
    patterns: ['anydesk', 'teamviewer', 'quicksupport', 'rustdesk', 'ultraviewer', 'fernwartung', 'fernzugriff', 'remote access'],
  },

  // ── Bezahlung ─────────────────────────────────────────────────────
  {
    id: 'gift_cards',
    group: 'payment',
    label: 'Bezahlung mit Gutschein- oder Guthabenkarten',
    weight: 0.58,
    categories: ['tech_support', 'romance', 'impersonation', 'advance_fee'],
    patterns: [
      '(?:google ?play|apple|itunes|amazon|steam|paysafe|neosurf|psn|xbox)[- ]?(?:karten?|gutscheine?|guthaben(?:karte)?|codes?|gift ?cards?)',
      'paysafecard',
      'gutscheinkarten?',
      'guthabenkarten?',
      'gift ?cards?',
    ],
  },
  {
    id: 'crypto',
    group: 'payment',
    label: 'Krypto-Zahlung oder Krypto-Wallet im Spiel',
    weight: 0.36,
    categories: ['investment', 'sextortion'],
    patterns: [
      'bitcoin',
      'btc',
      'usdt',
      'tether',
      'ethereum',
      'krypto-?(?:währung|wallet|börse|handel|trading)?',
      'crypto(?:currency)?',
      'wallet-?adresse',
      'binance',
    ],
  },
  {
    id: 'money_transfer',
    group: 'payment',
    label: 'Bargeldtransfer-Dienst oder Bargeld per Post',
    weight: 0.45,
    categories: ['advance_fee', 'romance', 'rental'],
    patterns: ['western union', 'moneygram', 'ria money', 'bargeld per post', 'geld per post', 'bargeld (?:abholen|übergeben) lassen'],
  },
  {
    id: 'paypal_ff',
    group: 'payment',
    label: 'PayPal „Freunde & Familie“ (kein Käuferschutz)',
    weight: 0.45,
    categories: ['marketplace', 'fake_shop'],
    patterns: ['freunde (?:und|&) familie', 'friends (?:and|&) family', 'paypal f&f', 'paypal ff'],
  },
  {
    id: 'prepayment',
    group: 'payment',
    label: 'Vorkasse oder Gebühr im Voraus',
    weight: 0.28,
    categories: ['advance_fee', 'fake_shop', 'rental'],
    patterns: [
      'vorkasse',
      'vorauskasse',
      'vorab (?:überweisen|zahlen|bezahlen|überwiesen)',
      'im voraus (?:überweisen|zahlen|bezahlen)',
      'anzahlung',
      'nur (?:per )?(?:überweisung|banküberweisung)',
      '(?:bearbeitungs|aktivierungs|freischalt|zoll|transfer|verwaltungs|vermittlungs|auszahlungs)gebühr(?:en)?',
      '(?:processing|release|customs|transfer) fee',
    ],
  },

  // ── Zu schön, um wahr zu sein ─────────────────────────────────────
  {
    id: 'unrealistic_returns',
    group: 'too_good',
    label: 'Unrealistische Gewinnversprechen',
    weight: 0.5,
    categories: ['investment'],
    patterns: [
      'garantiert(?:e|en)? (?:rendite|gewinne?|einnahmen|einkommen|profite?)',
      '\\d+(?:[.,]\\d+)? ?% (?:rendite|gewinn|profit|zinsen)(?: \\p{L}+){0,2} (?:pro |im |am |in der |jeden )?(?:tag|woche|monat)',
      'passives? einkommen',
      '(?:geld|investition|einsatz) (?:zu )?verdoppeln',
      'risikofrei',
      'ohne (?:jedes )?risiko',
      'guaranteed (?:returns?|profits?|income)',
      'double your (?:money|investment)',
      '(?:ki|ai|krypto)-?trading-?(?:bot|software|plattform)',
      'trading-?bot',
      'quantum ?ai',
      'bitcoin (?:code|era|prime|trader|evolution)',
      'immediate (?:edge|connect|momentum)',
      'finanzielle freiheit',
    ],
  },
  {
    id: 'easy_money',
    group: 'too_good',
    label: 'Leicht verdientes Geld ohne Erfahrung',
    weight: 0.36,
    categories: ['job'],
    patterns: [
      '\\d[\\d.,]* ?(?:€|euro|eur) (?:pro|am|im|je|/) ?(?:tag|stunde|std\\.?|woche|aufgabe)',
      '(?:€|eur) ?\\d[\\d.,]* (?:pro|am|im|je|/) ?(?:tag|stunde|woche|aufgabe)',
      'ohne (?:vor)?kenntnisse',
      'ohne (?:berufs)?erfahrung',
      'keine (?:vor)?(?:erfahrung|kenntnisse) (?:nötig|notwendig|erforderlich)',
      '(?:verdiene|verdienen sie|nebenverdienst)(?: \\p{L}+){0,4} (?:von zu ?hause|nebenbei|bequem|vom handy)',
      'nur \\d+ (?:minuten|stunden) (?:am|pro) tag',
      'work from home',
    ],
  },
  {
    id: 'prize',
    group: 'too_good',
    label: 'Angeblicher Gewinn oder Auswahl',
    weight: 0.45,
    categories: ['lottery', 'advance_fee'],
    patterns: [
      '(?:sie haben|du hast)(?: \\p{L}+){0,4} gewonnen',
      '(?:hauptgewinn|gewinnbenachrichtigung|gewinnspiel-?gewinner)',
      'glückwunsch(?:e)?(?: \\p{L}+){0,4} (?:gewonnen|ausgewählt|ausgelost)',
      '(?:wurden|wurdest) (?:als gewinner )?(?:ausgewählt|ausgelost)',
      "you(?:'ve| have) won",
      'lotterie',
      'lottery',
      'link in (?:unserer|meiner|der) bio',
    ],
  },
  {
    id: 'huge_discount',
    group: 'too_good',
    label: 'Extremer Rabatt',
    weight: 0.26,
    categories: ['fake_shop'],
    patterns: [
      '-? ?(?:[6-9]\\d) ?% (?:rabatt|reduziert|günstiger|off|sale)',
      'räumungsverkauf',
      'lagerräumung',
      'geschäftsaufgabe',
      'ausverkauf',
      'nur heute \\d+ ?%',
    ],
  },
  {
    id: 'inheritance',
    group: 'too_good',
    label: 'Erbschaft oder große Geldsumme von Unbekannten',
    weight: 0.52,
    categories: ['advance_fee'],
    patterns: [
      'erbschaft',
      'nachlass',
      'verstorbene[nr]? (?:kunden?|verwandten?|geschäftsmann)',
      'inheritance',
      'next of kin',
      '\\d+(?:[.,]\\d+)? ?millionen? (?:dollar|euro|usd|eur)',
    ],
  },

  // ── Typische Maschen ──────────────────────────────────────────────
  {
    id: 'off_platform',
    group: 'contact',
    label: 'Gespräch soll auf WhatsApp/Telegram/E-Mail wechseln',
    weight: 0.32,
    categories: ['marketplace', 'job', 'investment', 'romance'],
    patterns: [
      '(?:schreib|schreibe|schreiben sie|kontaktier|kontaktiere|kontaktieren sie|melde|melden sie)(?: \\p{L}+){0,4} (?:per|über|auf|via|bei) (?:whatsapp|telegram|signal|wechat|e-?mail)',
      '(?:per|über|auf|via) (?:whatsapp|telegram)',
      'whatsapp-?nummer',
      'telegram',
      'wa\\.me',
      't\\.me',
      'add me on',
      'text me on',
    ],
  },
  {
    id: 'marketplace_shipping',
    group: 'scheme',
    label: 'Bekannte Kleinanzeigen-Masche (Kurier, „Sicher bezahlen“-Link)',
    weight: 0.52,
    categories: ['marketplace'],
    patterns: [
      'sicher bezahlen(?: \\p{L}+){0,6} (?:link|formular|bestätig\\p{L}*)',
      '(?:link|formular|seite)(?: \\p{L}+){0,5} (?:um )?(?:das geld|die zahlung|den betrag) (?:zu )?(?:erhalten|empfangen|freizugeben)',
      'um (?:das geld|die zahlung|den betrag) zu (?:erhalten|empfangen)',
      '(?:spedition|kurier|kurierdienst|dhl|dpd|hermes|ups|gls)(?: \\p{L}+){0,6} (?:holt|abholen|abholung|bezahlt|übernimmt)',
      'ich bin (?:gerade |derzeit |zur zeit |leider )?beruflich unterwegs',
      'mein (?:sohn|neffe|cousin|bruder) (?:holt|kommt|wird)',
      'kreditkarte(?: \\p{L}+){0,4} (?:verifizieren|bestätigen)(?: \\p{L}+){0,4} (?:zahlung|geld)',
    ],
  },
  {
    id: 'abroad',
    group: 'abroad',
    label: 'Gegenüber ist angeblich im Ausland',
    weight: 0.28,
    categories: ['rental', 'romance', 'marketplace'],
    patterns: [
      'ich bin (?:gerade |derzeit |zur zeit |leider |beruflich )*(?:im ausland|auf montage|auf see)',
      '(?:beruflich|aus beruflichen gründen) (?:nach|ins) (?:\\p{L}+ ){0,2}(?:gezogen|versetzt|ausgewandert)',
      'lebe (?:derzeit |zurzeit |momentan )?im ausland',
    ],
  },
  {
    id: 'family_new_number',
    group: 'scheme',
    label: '„Hallo Mama/Papa, neue Nummer“-Masche',
    weight: 0.58,
    categories: ['family_emergency'],
    patterns: [
      '(?:hallo|hi|hey|huhu) (?:mama|mami|mutti|papa|papi|vati|mum|mom|dad|oma|opa)',
      '(?:meine|das ist meine|hab eine|habe eine) neue (?:handy)?nummer',
      'neue nummer(?: \\p{L}+){0,3} (?:speichern|eintragen)',
      'alte nummer(?: \\p{L}+){0,3} (?:löschen|nicht mehr)',
      'handy (?:ist )?(?:kaputt|ins wasser gefallen|ins klo gefallen|verloren|gestohlen)',
      '(?:kannst|könntest) du (?:mir )?(?:schnell |kurz )?(?:etwas |was )?(?:überweisen|auslegen|bezahlen)',
      'new number',
    ],
  },
  {
    id: 'romance',
    group: 'scheme',
    label: 'Typische Love-Scam-Elemente',
    weight: 0.34,
    categories: ['romance'],
    patterns: [
      '(?:mein|meine) (?:liebling|schatz|liebste[rs]?|engel)',
      'soldat\\p{L}*',
      'un-?(?:mission|einsatz)',
      'ölplattform',
      'offshore-?(?:plattform|einsatz)',
      'im (?:auslands)?einsatz',
      'flugticket',
      'zoll(?: \\p{L}+){0,3} (?:paket|freigabe)',
      'my (?:love|darling|dear)',
    ],
  },
  {
    id: 'tech_support',
    group: 'scheme',
    label: 'Falsche Virenwarnung / Fake-Support',
    weight: 0.52,
    categories: ['tech_support'],
    patterns: [
      '(?:ihr|dein) (?:computer|pc|gerät|rechner|handy|smartphone|iphone|mac)(?: \\p{L}+){0,2} (?:ist|wurde|wird) (?:mit \\p{L}+ )?(?:infiziert|gehackt|gesperrt|kompromittiert)',
      '(?:virus|viren|trojaner|malware) (?:gefunden|entdeckt|erkannt)',
      'microsoft[- ]?(?:support|sicherheit|techniker|defender-?warnung)',
      'windows[- ]?(?:support|sicherheitswarnung)',
      'apple[- ]?support(?:-?hotline)?',
      'rufen sie(?: \\p{L}+){0,4} (?:sofort|umgehend|jetzt) (?:an|unter)',
      'call (?:us|this number|support) (?:now|immediately)',
      'your (?:computer|pc|device) (?:is|has been) (?:infected|locked|compromised)',
    ],
  },
  {
    id: 'parcel',
    group: 'scheme',
    label: 'Paket-Benachrichtigung mit Handlungsaufforderung',
    weight: 0.32,
    categories: ['phishing'],
    patterns: [
      '(?:paket|sendung|lieferung|päckchen)(?: \\p{L}+){0,6} (?:nicht zugestellt|konnte nicht|zurückgehalten|angehalten|ausstehend|wartet|in der zollabfertigung)',
      '(?:adresse|lieferadresse|zustelladresse)(?: \\p{L}+){0,3} (?:bestätigen|aktualisieren|unvollständig|fehlerhaft)',
      '(?:versandkosten|zollgebühren|nachgebühr|lagergebühr)(?: \\p{L}+){0,3} (?:nachzahlen|ausstehend|offen|begleichen|bezahlen)',
      'parcel(?: \\p{L}+){0,4} (?:held|could not be delivered|pending)',
      'zustellversuch',
    ],
  },
  {
    id: 'job_task',
    group: 'scheme',
    label: 'Bekannte Job-Betrugsmasche',
    weight: 0.46,
    categories: ['job'],
    patterns: [
      '(?:bewertungen|rezensionen|reviews) (?:schreiben|abgeben|verfassen)',
      '(?:hotels?|produkte|apps?|restaurants?|videos?)(?: und \\p{L}+)? (?:zu )?bewerten',
      '(?:mentor|mentorin|trainer|betreuer|coach)(?: \\p{L}+){0,4} (?:auf|über|via|bei) (?:telegram|whatsapp)',
      'likes? (?:vergeben|sammeln|klicken)',
      'aufgaben-?(?:basiert|job|system|paket)',
      '(?:einfache|kleine) aufgaben',
      'produkttester(?:in)?',
      'paket-?agent(?:in)?',
      'waren-?agent(?:in)?',
      'app-?tester(?:in)?(?: \\p{L}+){0,4} (?:bezahlt|verdienen|vergütung)',
      'testauftr(?:ag|äge)(?: \\p{L}+){0,4} (?:video|ident|konto)',
      '(?:sie|du) (?:wurden|wurdest|bist) (?:für (?:eine|die) stelle )?ausgewählt',
      'recruiter(?: \\p{L}+){0,4} (?:whatsapp|telegram)',
    ],
  },
  {
    id: 'rental',
    group: 'scheme',
    label: 'Typische Wohnungsbetrugs-Masche',
    weight: 0.42,
    categories: ['rental'],
    patterns: [
      'schlüssel(?: \\p{L}+){0,3} (?:per|mit der|über die) post',
      'besichtigung (?:ist )?(?:leider )?(?:nicht möglich|erst nach)',
      'kaution(?: \\p{L}+){0,4} (?:vorab|vor der besichtigung|überweisen|treuhand)',
      'airbnb(?: \\p{L}+){0,4} (?:übergabe|zahlung|treuhand)',
      'treuhand(?:service|konto)?',
    ],
  },
  {
    id: 'sextortion',
    group: 'scheme',
    label: 'Erpressung mit angeblichen intimen Aufnahmen',
    weight: 0.6,
    categories: ['sextortion'],
    patterns: [
      '(?:video|aufnahme|aufzeichnung|bilder)(?: \\p{L}+){0,5} (?:webcam|kamera)',
      'pornografisch\\p{L}*',
      'porno\\p{L}*',
      'masturb\\p{L}*',
      'intime (?:bilder|fotos|videos|aufnahmen)',
      'an (?:alle )?(?:deine|ihre) kontakte (?:senden|schicken|verteilen|weiterleiten)',
      'ich habe (?:dein|ihr) (?:gerät|handy|konto|e-?mail-?konto|computer) gehackt',
      'i have (?:hacked|access to) your',
    ],
  },
  {
    id: 'subscription',
    group: 'scheme',
    label: 'Mögliche Abofalle',
    weight: 0.26,
    categories: ['subscription_trap'],
    patterns: [
      '(?:gratis|kostenlos|kostenfrei|for free)(?: \\p{L}+){0,5} (?:test|probe|abo|testphase)(?: \\p{L}+){0,6} (?:danach|anschließend|nach ablauf|verlängert sich)',
      'nur (?:die )?versandkosten',
      'probeabo',
      'verlängert sich automatisch',
    ],
  },
  {
    id: 'qr_code',
    group: 'scheme',
    label: 'QR-Code soll gescannt werden',
    weight: 0.24,
    categories: ['phishing'],
    patterns: ['qr-?code(?: \\p{L}+){0,4} (?:scannen|scan|einscannen)', 'scan(?:ne|nen sie)? (?:den|diesen) qr'],
  },
  {
    id: 'charity',
    group: 'scheme',
    label: 'Spendenaufruf mit unklarer Herkunft',
    weight: 0.25,
    categories: ['charity'],
    patterns: ['spenden sie (?:jetzt|sofort)', 'jeder euro (?:zählt|hilft)(?: \\p{L}+){0,6} (?:paypal|überweis)', 'spendenkonto(?: \\p{L}+){0,4} privat'],
  },

  // ── Stil & Form ───────────────────────────────────────────────────
  {
    id: 'generic_greeting',
    group: 'style',
    label: 'Unpersönliche Anrede',
    weight: 0.12,
    categories: ['phishing'],
    patterns: [
      'sehr geehrte[rs]? (?:kunde|kundin|nutzer|nutzerin|benutzer|kontoinhaber|mitglied|damen und herren)',
      'liebe[rs]? (?:kunde|kundin|nutzer|nutzerin|benutzer|mitglied)',
      'hallo (?:kunde|nutzer|benutzer)',
      'dear (?:customer|user|client|member|sir)',
    ],
  },
  {
    id: 'foreign_phone',
    group: 'style',
    label: 'Ausländische Telefonnummer',
    weight: 0.14,
    categories: ['other'],
    patterns: ['(?:\\+|00)(?!49|43|41|423|352)(?:\\d{1,3})[\\s\\d/-]{7,}'],
  },
];

/** Brands that are frequently impersonated, with their official registrable domains. */
export interface BrandInfo {
  name: string;
  /** Keywords that identify the brand in hostnames (labels or label prefixes). */
  tokens: string[];
  /** Keywords that identify the brand in plain text. */
  textPatterns: string[];
  official: RegExp;
  /** Messaging/social platforms: mentioning them in text is normal, so only hostnames count. */
  platform?: boolean;
}

export const BRANDS: BrandInfo[] = [
  { name: 'DHL', tokens: ['dhl'], textPatterns: ['dhl'], official: /^(?:dhl\.(?:de|com|at|ch)|deutschepost\.de|dpdhl\.com)$/ },
  { name: 'Deutsche Post', tokens: ['deutschepost', 'deutsche-post'], textPatterns: ['deutsche post'], official: /^(?:deutschepost\.de|dhl\.de)$/ },
  { name: 'DPD', tokens: ['dpd'], textPatterns: ['dpd'], official: /^dpd\.(?:de|com|at|ch)$/ },
  { name: 'Hermes', tokens: ['hermes', 'myhermes'], textPatterns: ['hermes'], official: /^(?:myhermes\.de|hermesworld\.com|hermes-europe\.eu)$/ },
  { name: 'GLS', tokens: ['gls'], textPatterns: ['gls'], official: /^(?:gls-pakete\.de|gls-group\.(?:eu|com)|gls-austria\.com)$/ },
  { name: 'UPS', tokens: ['ups'], textPatterns: ['ups'], official: /^ups\.com$/ },
  { name: 'PayPal', tokens: ['paypal'], textPatterns: ['paypal'], official: /^(?:paypal\.(?:com|de|at|ch|me)|paypalobjects\.com)$/ },
  { name: 'Amazon', tokens: ['amazon', 'amzn'], textPatterns: ['amazon'], official: /^(?:amazon\.(?:de|com|at|co\.uk|fr|it|es|nl)|amzn\.(?:to|eu|com)|a\.co)$/ },
  { name: 'eBay', tokens: ['ebay'], textPatterns: ['ebay'], official: /^ebay\.(?:de|com|at|ch)$/ },
  { name: 'Kleinanzeigen', tokens: ['kleinanzeigen', 'ebay-kleinanzeigen'], textPatterns: ['kleinanzeigen'], official: /^(?:kleinanzeigen\.de|ebay-kleinanzeigen\.de)$/ },
  { name: 'Vinted', tokens: ['vinted'], textPatterns: ['vinted'], official: /^vinted\.(?:de|com|at|fr)$/ },
  { name: 'Apple', tokens: ['apple', 'icloud', 'itunes'], textPatterns: ['apple', 'icloud'], official: /^(?:apple\.com|icloud\.com)$/ },
  { name: 'Microsoft', tokens: ['microsoft', 'outlook', 'office365', 'hotmail'], textPatterns: ['microsoft', 'outlook'], official: /^(?:microsoft\.com|live\.com|outlook\.com|office\.com|microsoftonline\.com)$/ },
  { name: 'Netflix', tokens: ['netflix'], textPatterns: ['netflix'], official: /^netflix\.com$/ },
  { name: 'Sparkasse', tokens: ['sparkasse', 'sparkassen'], textPatterns: ['sparkasse'], official: /^(?:sparkasse(?:-[a-z0-9-]+)?\.(?:de|at)|s-[a-z0-9-]+\.de|ksk-[a-z0-9-]+\.de)$/ },
  { name: 'Volksbank', tokens: ['volksbank', 'vrbank', 'raiffeisen'], textPatterns: ['volksbank', 'raiffeisenbank', 'vr-bank'], official: /^(?:(?:volksbank|vb|vr|vrbank|raiffeisenbank|rb)(?:-[a-z0-9-]+)?\.(?:de|at)|vr\.de)$/ },
  { name: 'Postbank', tokens: ['postbank'], textPatterns: ['postbank'], official: /^postbank\.de$/ },
  { name: 'Commerzbank', tokens: ['commerzbank'], textPatterns: ['commerzbank'], official: /^commerzbank\.(?:de|com)$/ },
  { name: 'Deutsche Bank', tokens: ['deutschebank', 'deutsche-bank'], textPatterns: ['deutsche bank'], official: /^(?:deutsche-bank\.de|db\.com)$/ },
  { name: 'DKB', tokens: ['dkb'], textPatterns: ['dkb'], official: /^dkb\.de$/ },
  { name: 'ING', tokens: ['ing-diba', 'ingdiba'], textPatterns: ['ing-diba', 'ing diba'], official: /^ing\.(?:de|at)$/ },
  { name: 'N26', tokens: ['n26'], textPatterns: ['n26'], official: /^n26\.com$/ },
  { name: 'comdirect', tokens: ['comdirect'], textPatterns: ['comdirect'], official: /^comdirect\.de$/ },
  { name: 'Telekom', tokens: ['telekom', 't-online'], textPatterns: ['telekom'], official: /^(?:telekom\.(?:de|com)|t-online\.de)$/ },
  { name: 'Vodafone', tokens: ['vodafone'], textPatterns: ['vodafone'], official: /^vodafone\.(?:de|com|at)$/ },
  { name: 'ELSTER / Finanzamt', tokens: ['elster', 'finanzamt', 'bzst'], textPatterns: ['elster', 'finanzamt', 'bundeszentralamt'], official: /^(?:elster\.de|bzst\.de|bund\.de|[a-z-]+\.bund\.de)$/ },
  { name: 'Zoll', tokens: ['zoll'], textPatterns: ['zoll'], official: /^zoll\.de$/ },
  { name: 'WhatsApp', tokens: ['whatsapp'], textPatterns: ['whatsapp'], official: /^(?:whatsapp\.com|wa\.me)$/, platform: true },
  { name: 'Instagram', tokens: ['instagram'], textPatterns: ['instagram'], official: /^instagram\.com$/, platform: true },
  { name: 'Facebook / Meta', tokens: ['facebook'], textPatterns: ['facebook'], official: /^(?:facebook\.com|fb\.com|meta\.com|fb\.me)$/, platform: true },
  { name: 'Google', tokens: ['google', 'gmail'], textPatterns: ['google'], official: /^(?:google\.(?:com|de|at|ch)|gmail\.com|youtube\.com|goo\.gl)$/, platform: true },
  { name: 'Booking.com', tokens: ['booking'], textPatterns: ['booking.com'], official: /^booking\.com$/ },
  { name: 'Airbnb', tokens: ['airbnb'], textPatterns: ['airbnb'], official: /^airbnb\.(?:de|com|at|ch)$/ },
  { name: 'Coinbase', tokens: ['coinbase'], textPatterns: ['coinbase'], official: /^coinbase\.com$/ },
  { name: 'Binance', tokens: ['binance'], textPatterns: ['binance'], official: /^binance\.com$/ },
];

export const URL_SHORTENERS = new Set([
  'bit.ly',
  'tinyurl.com',
  'goo.gl',
  'ow.ly',
  'is.gd',
  'cutt.ly',
  'rebrand.ly',
  's.id',
  't.ly',
  'shorturl.at',
  'rb.gy',
  'tiny.cc',
  'bit.do',
  'v.gd',
  'buff.ly',
  'shorte.st',
  'adf.ly',
  'qrco.de',
  'linktr.ee',
  'l.ead.me',
  'tiny.one',
]);

export const RISKY_TLDS = new Set([
  'xyz',
  'top',
  'click',
  'link',
  'icu',
  'buzz',
  'live',
  'online',
  'site',
  'website',
  'monster',
  'rest',
  'cyou',
  'sbs',
  'cfd',
  'bond',
  'tk',
  'ml',
  'ga',
  'cf',
  'gq',
  'pw',
  'su',
  'zip',
  'mov',
  'loan',
  'win',
  'bid',
  'vip',
  'fun',
  'support',
  'help',
]);

/** Bare domains (without http/www) are only treated as links for these TLDs to avoid false positives like "bild.zip". */
export const BARE_DOMAIN_TLDS = new Set([
  'de', 'com', 'net', 'org', 'at', 'ch', 'eu', 'info', 'io', 'co', 'me', 'biz', 'app', 'shop', 'store',
  'online', 'site', 'xyz', 'top', 'click', 'link', 'live', 'icu', 'buzz', 'vip', 'club', 'website', 'fun',
  'ru', 'cn', 'tk', 'ml', 'ga', 'cf', 'gq', 'pw', 'su', 'cc', 'ws', 'nl', 'fr', 'it', 'es', 'pl', 'uk',
  'sbs', 'cfd', 'cyou', 'bond', 'monster', 'rest', 'support', 'help',
]);

export const PHISHY_HOST_WORDS = [
  'login',
  'signin',
  'secure',
  'sicher',
  'verify',
  'verifizierung',
  'verification',
  'update',
  'account',
  'konto',
  'bestaetigung',
  'bestatigung',
  'support',
  'kundenservice',
  'service-center',
  'zahlung',
  'payment',
  'tracking',
  'sendung',
  'paket',
  'zustellung',
  'zoll',
  'refund',
  'erstattung',
  'auth',
  'wallet',
];
